{{- if .Values.serviceMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: emqx
    app.kubernetes.io/instance: emqx-{{ .Release.Namespace }}
    app.kubernetes.io/name: emqx
  name: emqx-svcm
spec:
  endpoints:
  - port: dashboard
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    path: /api/v5/prometheus/stats
    honorLabels: {{ .Values.serviceMonitor.honorLabels }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- tpl (toYaml .Values.serviceMonitor.metricRelabelings | nindent 4) . }}
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings:
    {{ toYaml .Values.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: emqx-{{ .Release.Namespace }}
      app.kubernetes.io/name: emqx
      app.kubernetes.io/managed-by: Helm
{{ end }}
